### ISSUE TITLE
Better error messages for `Spy.COMPARE`

### ISSUE THREAD

**Issue by LinuCC** [fdc-viktor-luft/spy4js#1]
Currently error messages for failing manually defined `Spy.COMPARE`s are a bit cryptic:

```js
 dispatchSpy was considered to be called with the following arguments in the given order:

    call 0: [SpyComparator{_func: Function}]

    Actually there were:

    call 0: [{type: 'ADD_MESSAGE', data: <···>}]
            --> 0 / custom comparison failed
```

A possible solution would be to place the `custom comparison failed` more prominently, or change the whole message so the error message is specific to the custom comparator.

**Comment by fdc-viktor-luft** [comment]
I worked out [something](https://github.com/fdc-viktor-luft/spy4js/releases/tag/v.2.7.0). And I would like to hear about your feedback.
